spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    include: oauth, secret
  servlet:
    multipart:
      # 파일 업로드 기능여부 선택
      enabled: true
      # 파일 하나의 최대 크기
      max-file-size: 100MB
      # 한번에 최대 업로드 가능 용량
      max-request-size: 100MB
      location: C:\tempImg
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
com:
  example:
    upload:
      path: C:\tempImg\